### PR TITLE
Upgrade dotnet/docker-tool to 8fa03e2

### PR DESCRIPTION
**Pull request by qmuntal**
The go-infra-images validation pipeline is currently failing because the checked in dotnet/docker-tools version is too old: https://dev.azure.com/dnceng/internal/_build/results?buildId=2431394&view=results.

This PR upgrades  dotnet/docker-tools to [8fa03e2](https://github.com/dotnet/docker-tools/commit/8fa03e26afbf7676865f2335c0b2f78baf5dbfe9) and updates our image pool selection accordingly.

### CODE REVIEW

**Review by dagood — APPROVED** [review]
Did you run a test build with this change?

**Review by gdams — APPROVED** [review]

**Comment by dagood** [comment]
Granted, and I went through the `go-*` variable groups to fix up some old permissions.

**Comment by qmuntal** [comment]
Building cbl-mariner fails due to our friend `curl#60: SSL peer certificate or SSH remote key was not OK`: https://dev.azure.com/dnceng/internal/_build/results?buildId=2441331&view=logs&j=fc59f0f2-c1bd-58ae-b870-833d1e8a924c&t=8d53baa0-ff68-5ea5-041a-af0e08303d7f&l=256.

@dagood you recently investigated this failure mode in another context. Any idea to get it fixed?

**Comment by dagood** [comment]
My first guess is that it's because we're trying to use a Mariner 1.0 image, but 1.0 is EOL so its repositories are offline (or lack cert updates, etc.). Updating to 2.0 is probably the right fix.

**Pull request merged**
